import type { Metadata } from "next";
import { Analytics } from "@vercel/analytics/react"
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const inter = localFont({
  src: "./fonts/InterVariable.ttf",
  variable: "--font-inter",
  weight: "100 200 300 400 500 600 700 800 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 

  {

  console.log(`
    WEBSITE DESIGNED BY: 

    ██████  ██████  ██    ██ ██████  ███████ ███    ██     ██████     
    ██   ██ ██   ██  ██  ██  ██   ██ ██      ████   ██     ██   ██    
    ██   ██ ██████    ████   ██   ██ █████   ██ ██  ██     ██████     
    ██   ██ ██   ██    ██    ██   ██ ██      ██  ██ ██     ██   ██    
    ██████  ██   ██    ██    ██████  ███████ ██   ████     ██████  ██ 
    
    LinkedIn: https://www.linkedin.com/in/drydenbryson/
    GitHub:   https://github.com/Dryd33n
    `)

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} font-sans antialiased bg-[#0a0a0a]`}
      >
        <Analytics/>
        {children}
      </body>
    </html>
  );
}
